name: Generate Snake

on:
  schedule: # Run workflow every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: MohdRasmil7
          output: github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          git config --local user.email "muhammedrasmil2001@gmail.com"
          git config --local user.name "GitHub Action"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push
